kind: Pod
apiVersion: v1
metadata:
  name: pod-longhorn-delete
spec:
  volumes:
    - name: longhorn-pvc-delete
      persistentVolumeClaim:
        claimName: longhorn-pvc-delete
  containers:
    - name: my-container
      volumeMounts:
        - name: longhorn-pvc-delete # This is the name of the volume we set at the pod level
          mountPath: /var/simple # Where to mount this directory in our container
      image: alpine:3.20.0
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/simple/file.txt; sleep 5; done"]
      resources:
        limits:
          memory: 250Mi
          cpu: 250m
        requests:
          memory: 125Mi
          cpu: 125m
