FROM jenkins/agent:3206.vb_15dcf73f6a_9-9-alpine-jdk17 as base

# isntall nodejs
USER root
ENV NODE_VERSION=16.20.2
RUN mkdir /usr/local/nvm
ENV NVM_DIR /usr/local/nvm
RUN curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
# Verify Node.js and npm installation
RUN node --version
RUN npm --version

#back to jenkins user
USER jenkins