apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-service
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  clusterIP: None # headless services
  selector:
    app: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-normal-service
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
