apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html
  namespace: default
data:
  index.html: |
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
    </head>
    <body>
        This is nginx content
    </body>
    </html>

