apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-ipaddresspool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.56.200-192.168.56.254

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: first-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-ipaddresspool
