# kubectl autoscale deployment backend --min=2 --max=5 --cpu-percent=60 --dry-run=client -o yaml
{{- $root := . -}}
{{ range $key, $value := .Values.metricServerEnable }}
{{- if $value }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $key }}

{{- with get $root.Values.horizontalPortCscale $key }}
spec:
{{- toYaml . | nindent 2 }}
{{- end }} # end with

{{- end }} # end if
---
{{- end }} # end range
