apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistenVolumeClaim.name }}
spec:
  storageClassName: {{ .Values.persistenVolumeClaim.storageClassName }}
  # config access mode
  {{- with .Values.persistenVolumeClaim.accessModes }}
  accessModes:
  {{- toYaml . | nindent 4 }}
  {{- end }}

  # config resources
  {{- with .Values.persistenVolumeClaim.resources }}
  resources:
  {{- toYaml . | nindent 4 }}
  {{- end }}