apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-nodeport
  name: frontend-nodeport
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend
  type: NodePort
