apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  # policy.default: role:readonly
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow
    p, role:org-admin, projects, get, *, allow
    p, role:org-admin, projects, create, *, allow
    p, role:org-admin, projects, update, *, allow
    p, role:org-admin, projects, delete, *, allow
    p, role:org-admin, logs, get, *, allow
    p, role:org-admin, exec, create, */*, allow

    p, role:kustomize-user, applications, create, kustomize-dev-project/*, allow
    p, role:kustomize-user, applications, delete, kustomize-dev-project/*, allow
    p, role:kustomize-user, applications, get, kustomize-dev-project/*, allow
    p, role:kustomize-user, applications, override, kustomize-dev-project/*, allow
    p, role:kustomize-user, applications, sync, kustomize-dev-project/*, allow
    p, role:kustomize-user, applications, update, kustomize-dev-project/*, allow
    p, role:kustomize-user, logs, get, kustomize-dev-project/*, allow
    p, role:kustomize-user, exec, create, kustomize-dev-project/*, allow
    p, role:kustomize-user, projects, get, kustomize-dev-project, allow
    g, kustomize-user, role:kustomize-user
    g, kustomize-admin, role:kustomize-user


    p, role:kustomize-admin, applications, create, kustomize-prod-project/*, allow
    p, role:kustomize-admin, applications, delete, kustomize-prod-project/*, allow
    p, role:kustomize-admin, applications, get, kustomize-prod-project/*, allow
    p, role:kustomize-admin, applications, override, kustomize-prod-project/*, allow
    p, role:kustomize-admin, applications, sync, kustomize-prod-project/*, allow
    p, role:kustomize-admin, applications, update, kustomize-prod-project/*, allow
    p, role:kustomize-admin, logs, get, kustomize-prod-project/*, allow
    p, role:kustomize-admin, exec, create, kustomize-prod-project/*, allow
    p, role:kustomize-admin, projects, get, kustomize-prod-project, allow
    g, kustomize-admin, role:kustomize-admin