# kubectl create role argocd-all-access --verb='*' --resource='*' --dry-run -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-all-access
rules:
  - apiGroups: 
    # - ""
    # - "apps"
    # - "batch"
    # - "networking.k8s.io"
    - "*"
    resources: ["*"]
    verbs: ["*"]

  # - nonResourceURLs: ["*"]
  #   resources: []
  #   verbs: ["*"]