apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31000
  selector:
    app: todo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: python-todo
          image: kunchalavikram/python_todo_app:v2
          ports:
            - containerPort: 5000
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 200Mi
              cpu: 200m
            requests:
              memory: 100Mi
              cpu: 100m
          env:
          - name: DATABASE_URI
            value: 'mysql+pymysql://duongdx:duongdx1@mysql-normal.default.svc.cluster.local:3306/todo'

# URI: mysql://user:password@hostname:3306/database