- name: Setup load balancers
  hosts: load_balancer
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: Install haproxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Configure haproxy
      template:
        src: ../templates/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg

    - name: create haproxy ssl
      file:
        state: directory
        dest: /etc/haproxy/ssl

    - name: Configure haproxy ssl
      template:
        src: ../sign-yourself/duongdx.pem
        dest: /etc/haproxy/ssl/duongdx.pem

    - name: Restart haproxy
      systemd:
        name: haproxy
        state: restarted
        enabled: yes
        daemon-reload: yes

    # Keepalived for Virtual IP
    - name: Install keepalived
      apt:
        name:
          - keepalived
        state: present
        update_cache: yes

    - name: Create master keepalived.conf
      template:
        src: ../templates/keepalived.conf
        dest: /etc/keepalived/keepalived.conf
      vars: 
        keepalived_state:  "{{ keepalived_master_state }}"
        keepalived_priority: "{{ keepalived_priority_default }}"
      when: inventory_hostname == haproxy_master_name
      notify: Restart keepalived

    - name: Create backup keepalived.conf
      template:
        src: ../templates/keepalived.conf
        dest: /etc/keepalived/keepalived.conf
      vars:
        keepalived_state: "{{ keepalived_backup_state }}"
        keepalived_priority: "{{ keepalived_priority_default - ansible_play_hosts_all.index(inventory_hostname) * 66 }}"
      when: inventory_hostname != haproxy_master_name
      notify: Restart keepalived

    - name: Restart keepalived
      systemd:
        name: keepalived
        state: restarted
        enabled: yes
        daemon-reload: yes

  handlers:
    - name: Restart keepalived
      systemd:
        name: keepalived
        state: restarted
        enabled: yes
        daemon-reload: yes