- name: install prerequisite jenkins
  hosts: jenkins_master
  vars_files:
    - vars.yaml
  tasks:
    # Start: install container runtime
    - name: Uninstall old versions
      apt:
        name:
          - docker.io
          - docker-compose
          - docker-compose-v2
          - docker-doc
          - podman-docker
        state: absent

    - name: Install prerequisite for container run time
      apt:
        name:
          - curl
          - vim
          - gpg
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present
        update_cache: yes # this option is the same 'apt-get update'

    - name: make directory for saving key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        keyring: "/etc/apt/keyrings/docker.gpg"
        url: "https://download.docker.com/linux/{{ os_version }}/gpg"

    - name: Add Docker Repository
      lineinfile:
        path: "/etc/apt/sources.list.d/docker.list"
        line: "deb [arch={{ architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        {{ docker_version_code_name }} stable"
        create: yes

    # kubernetes only need container.io as container runtime
    - name: Update apt and install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: enabled && restart docker
      service:
        name: docker
        state: restarted
        enabled: true

    - name: adding existing user '{{ ansible_user }}' to group docker
      user:
        name: '{{ ansible_user }}'
        groups: docker
        append: yes

########################################################################3
# run for docker-agent:
# create network: docker network create jenkins
# docker run --name docker-agent -d --restart=always -p 127.0.0.1:2376:2375 --network jenkins -v /var/run/docker.sock:/var/run/docker.sock alpine/socat tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
########################################################################
    