- name: Worker node configuration and join node
  become: yes
  hosts: worker_node
  tasks:
  - name: Copy token to worker nodes
    copy:
      src: /tmp/kubernetes_join_command
      dest: /tmp/kubernetes_join_command
      mode: 0777

  - name: Resetting kubeadm
    shell: kubeadm reset -f

  - name: Join the Worker nodes with the master.
    command: sh /tmp/kubernetes_join_command
    register: joined_or_not

  - debug:
      msg: "{{ joined_or_not.stdout }}"

  # find / -name 10-kubeadm.conf
  - name: Edit kubeadm.conf - config node ip
    lineinfile:
      path: '/lib/systemd/system/kubelet.service.d/10-kubeadm.conf'
      line: 'Environment="KUBELET_EXTRA_ARGS=--node-ip={{ ansible_host }}"'
      regexp: 'KUBELET_EXTRA_ARGS='
      insertafter: '\[Service\]'
      state: present
    notify: restart kubelet

  handlers:
    - name: restart kubelet
      systemd:
        state: restarted
        name: kubelet
        daemon_reload: true