- name: setup master and workers
  hosts: master_node, worker_node
  become: true
  tasks:
    - name: Disable swap
      shell: swapoff -a

    - name: Remove swap
      lineinfile:
        dest: /etc/fstab
        regexp: swap
        status: absent

    # Start: prerequisite configuration  container runtime
    # https://kubernetes.io/docs/setup/production-environment/container-runtimes/
    - name: config bt_netfilter module
      shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF

    - name: configure iptables to see bridged traffic
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
        EOF

    - name: Apply sysctl params without reboot
      shell: sudo sysctl --system

    # End: prerequisite for container runtime

    # ---
    # Start: install container runtime
    - name: Uninstall old versions
      apt:
        name:
          - docker.io
          - docker-compose
          - docker-compose-v2
          - docker-doc
          - podman-docker
        status: absent

    - name: Install prerequisite for container run time
      apt:
        name:
          - curl
          - vim
          - ca-certificates
        state: present
        update_cache: yes # this option is the same 'apt-get update'

    - name: Add Docker GPG apt Key
      get_curl:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/apt/keyrings/docker.asc
        mode: '0755'

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    # kubernetes only need container.io as container runtime
    - name: Update apt and install containerd.io
      apt:
        name: containerd.io
        state: latest
        update_cache: true
