concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "xuanduong_docker_in_docker"
  url = "https://gitlab.com/"
  id = 35122401
  token = "xxxxxxxxxxxxxxxxxxx"
  token_obtained_at = 2024-04-23T06:44:30Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  environment = ["RUNNER_DOCKER_SERVICES_LIMIT=0"]
  [runners.custom_build_dir]
  [runners.cache]
    Type = "s3"
    Path = "runner/cache"
    Shared = true
    [runners.cache.s3]
	AccessKey = "zXqw0b6fyihpEtXVonhM"
    	SecretKey = "k2VTiEWLanukywyDXb3P2jutFy4otnu2CtgLPkR0"
    	BucketName = "gitlab-runner-cache"
    	Insecure = true  # Set to true if using HTTP (not recommended for production)
    	ServerAddress = "192.168.56.98:9000"  # Replace with your MinIO server address
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache","/var/run/docker.sock:/var/run/docker.sock"]
    services_limit = 2
    shm_size = 0
    network_mtu = 0
    pull_policy = ["if-not-present"] # noticed that configuration

