version: '3.8'

# docker run -d --name gitlab-runner --restart always \
#  -v /var/run/docker.sock:/var/run/docker.sock \
#  -v /srv/gitlab-runner/config:/etc/gitlab-runner \
#  gitlab/gitlab-runner:alpine

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    container_name: gitlab-runner
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - gitlab-runner

  minio:
    image: minio/minio:RELEASE.2024-03-10T02-53-48Z
    container_name: minio
    networks: 
      - gitlab-runner
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: minio server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks: 
      - gitlab-runner
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_ALIAS_NAME=${MINIO_ALIAS_NAME}
    entrypoint: >
      /bin/sh -c "
      printenv;
      /usr/bin/mc config host add $MINIO_ALIAS_NAME http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc config host anonymous enable $MINIO_ALIAS_NAME;
      /usr/bin/mc rm -r --force $MINIO_ALIAS_NAME/$MINIO_BUCKET_NAME >> /dev/null 2>&1;
      /usr/bin/mc mb $MINIO_ALIAS_NAME/$MINIO_BUCKET_NAME >> /dev/null 2>&1;
      /usr/bin/mc policy download $MINIO_ALIAS_NAME/$MINIO_BUCKET_NAME;
      exit 0;
      "

networks:
  gitlab-runner:
    name: gitlab-runner

volumes:
  minio_data: {}