apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kustomize-dev-project
  namespace: argocd
spec:
  description: this  project only supports duongdx-kustomize product

  sourceRepos:
  - https://github.com/duongdx-kma/k8s-manifetst-argocd-test.git

  destinations:
  - namespace: kustomize-dev
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app-dev
  namespace: argocd
spec:
  destination:
    namespace: kustomize-dev
    server: https://kubernetes.default.svc
  project: kustomize-dev-project
  source:
    repoURL: https://github.com/duongdx-kma/k8s-manifetst-argocd-test.git
    targetRevision: main
    path:  kustomize/overlays/dev
    kustomize:
      namePrefix: dev-
      nameSuffix: -v1
      namespace: kustomize-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app-dev
  namespace: argocd
spec:
  destination:
    namespace: kustomize-dev
    server: https://kubernetes.default.svc
  project: kustomize-dev-project
  source:
    repoURL: https://github.com/duongdx-kma/k8s-manifetst-argocd-test.git
    targetRevision: main
    path:  kustomize/overlays/dev
    kustomize:
      namePrefix: dev-
      nameSuffix: -v1
      namespace: kustomize-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true