apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-ui-application-fail-on-shared-resources
  namespace: argocd
spec:
  destination:
    namespace: web-ui
    server: https://kubernetes.default.svc
  project: default
  source:
    path: web-ui
    repoURL: git@github.com:duongdx-kma/k8s-manifetst-argocd-test.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true #argocd.argoproj.io/sync-options: ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true #argocd.argoproj.io/sync-options: FailOnSharedResource=true
    automated:
      prune: true # argocd.argoproj.io/sync-options: Prune=true
      selfHeal: true