# configmap
{{ range $key, $value := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $value.name }}

{{- with $value.data }}
data:
{{- toYaml . | nindent 2 }}
{{- end }}

---
{{- end}}