{{- $root := . -}} # use default value
{{ range $key, $value := .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with $value.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $value.name }}
spec:
  ingressClassName: {{ $value.className }}
  rules:
  - http:
      {{- with $value.paths }}
      paths:
      {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
