{{- $root := . -}} # use default value
{{ range $key, $value := .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with $value.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $value.name }}
spec:
  ingressClassName: {{ $value.className }}
  {{- with $value.rules }}
  rules:
  {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
