{{- $root := . -}} # use default value
{{ range $key, $value := .Values.image.repositories }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
  {{- with $value.labels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $value.serviceType }}
  {{- with $value.servicePort }}
  ports:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $value.labels }}
  selector:
  {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end}}